version: '3'
services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis:
    hostname: redis
    command: redis-server --requirepass password
    image: 'redis:6-alpine'
    ports:
      - "6379:6379"
    volumes:
        - redis-data:/data
  webserver:
    container_name: webserver
    image: webserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - "redis"
    depends_on:
      - redis
volumes:
  redis-data: